# Generated by Django 3.1 on 2020-08-16 05:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=20)),
                ('end', models.CharField(max_length=20)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='DriveNodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osmid', models.CharField(max_length=20)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='WalkNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=20)),
                ('end', models.CharField(max_length=20)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='WalkNodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osmid', models.CharField(max_length=20)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='Nodes',
        ),
        migrations.DeleteModel(
            name='Streets',
        ),
    ]
