# Generated by Django 3.1 on 2020-08-17 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route_api', '0002_auto_20200816_0138'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WalkNetwork',
        ),
        migrations.DeleteModel(
            name='WalkNodes',
        ),
    ]
